[package]
name = "sawbill"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"

[dependencies.pnet]
version = "0.28.0"

[dependencies.redis]
version = "*"